version: "3.8"
services:

  goprx:
    hostname: goprx
    container_name: goprx
    build: 
      dockerfile: ./dockerfile.yaml
      context: ./
    ports:
      - "443:443"
    restart: unless-stopped
    environment:
      REDIS_PORT: "${REDIS_PORT}"
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      REDIS_ADDR: "${REDIS_ADDR}"
    deploy:
      resources:
        limits:
          memory: 200M
    networks:
      - prx  
    depends_on:
      - dragonfly

  dragonfly:
    hostname: dragonfly
    container_name: dragonfly
    image: "docker.dragonflydb.io/dragonflydb/dragonfly"
    ulimits:
      memlock: -1
    ports:
      - ${REDIS_PORT}
    command: >
      --bind localhost
      --dir data
      --dbfilename dump
      --requirepass ${REDIS_PASSWORD} 
      --port ${REDIS_PORT}
    volumes:
      - ./data:/data
    networks:
      - prx
    restart: unless-stopped
  
  http:
    image: "jdkelley/simple-http-server:latest"
    hostname: test
    container_name: test
    ports: 
      - 8000
    volumes: 
      - ./index.html:/server/index.html
    networks:
      - prx

networks:
    prx:
      external: false

volumes:
  dragonflydata:
