version: "3.8"
services:

  goprx:
    build:
      dockerfile: ./go_proxy.dockerfile
      context: .
    command: >
      ./main
      --record
      localhost=http://isthisworking:80
    ports:
      - "443:443"
    networks:
      - goprx
    restart: unless-stopped

  httpd:
    image: httpd:2.4
    container_name: isthisworking
    hostname: isthisworking
    ports:
      - "80"
    networks:
      - goprx  
    restart: unless-stopped

networks:
  goprx:
    external: false